version: "3.1"
services:
    www:
        build: ./docker
        ports:
            - "${WWW_PORT}:80"
        volumes:
            - ./:/var/www/html/
        links:
            - mariadb5
        networks:
            - default
    mariadb5:
        image: mariadb:5.5.56
        ports:
            - "${DB_PORT}:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mariadb5:/var/lib/mysql
    myadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mariadb5:db
        ports:
            - ${MY_ADMIN_PORT}:80
        environment:
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
volumes:
    mariadb5:
